-- SIGCP - estrutura relacional completa para Supabase/PostgreSQL.
-- Execute TODO este ficheiro no SQL Editor do Supabase.
drop table if exists public.sigcp_databases cascade; -- remove o contentor JSON antigo

create table if not exists public.utilizadores (
 id bigint generated by default as identity primary key, nim text not null unique,
 posto text, nome text, sobrenome text, data_chegada text, data_partida text,
 tipo_acesso text not null, password_salt text not null, password_hash text not null,
 master integer default 0, criado_em text default current_timestamp::text,
 antiguidade text, snr integer default 0, telemovel_servico text,
 responsavel_welfare integer default 0, area_funcional text default 'Não definido',
 ferias_direito_override double precision, missao_prorrogada integer default 0,
 notas_ferias text, snr_substituto integer default 0, snr_substituto_inicio text,
 snr_substituto_fim text, posicao_numero text, data_nascimento text
);
create table if not exists public.app_settings (chave text primary key, valor text, atualizado_em text default current_timestamp::text);
create table if not exists public.teams (
 id bigint generated by default as identity primary key, nome text not null unique,
 criado_em text default current_timestamp::text
);
create table if not exists public.welfares (
 id bigint generated by default as identity primary key, data text not null, refeicao text not null,
 tipo text not null, prato text, sobremesa text, observacao text,
 criado_em text default current_timestamp::text, team_id bigint references public.teams(id) on delete set null,
 recanto integer not null default 0, local text not null default '', unique(data, refeicao)
);
alter table public.welfares add column if not exists team_id bigint references public.teams(id) on delete set null;
alter table public.welfares add column if not exists recanto integer not null default 0;
alter table public.welfares add column if not exists local text not null default '';
create table if not exists public.team_membros (
 team_id bigint not null references public.teams(id) on delete cascade,
 utilizador_id bigint not null unique references public.utilizadores(id) on delete cascade,
 criado_em text default current_timestamp::text, primary key(team_id, utilizador_id)
);
create table if not exists public.escala_loica (
 fim_semana text primary key,
 militar_1_id bigint references public.utilizadores(id) on delete set null,
 militar_2_id bigint references public.utilizadores(id) on delete set null,
 assinatura_1 integer not null default 0, assinatura_2 integer not null default 0,
 validada integer not null default 0, manual integer not null default 0,
 atualizado_em text default current_timestamp::text
);
create table if not exists public.caixa_movimentos (
 id bigint generated by default as identity primary key,
 tipo text not null check(tipo in ('entrada','saida')), data text not null,
 pessoa_gasto text not null default '', local text not null default '',
 valor double precision not null check(valor > 0), descritivo text not null,
 observacoes text not null default '',
 criado_por_id bigint references public.utilizadores(id) on delete set null,
 criado_por_nome text not null default '', criado_em text not null default current_timestamp::text,
 atualizado_por_id bigint references public.utilizadores(id) on delete set null,
 atualizado_por_nome text not null default '', atualizado_em text not null default current_timestamp::text
);
create index if not exists idx_caixa_data on public.caixa_movimentos(data, id);
create table if not exists public.day_offs (
 id bigint generated by default as identity primary key, data text not null unique, observacao text,
 criado_em text default current_timestamp::text, atualizado_em text default current_timestamp::text
);
create table if not exists public.feriados (
 id bigint generated by default as identity primary key, data text not null unique,
 descricao text not null, ativo integer not null default 1,
 criado_em text default current_timestamp::text, atualizado_em text default current_timestamp::text
);
create table if not exists public.meses_trancados (mes text primary key, trancado integer not null default 0, atualizado_em text default current_timestamp::text);
create table if not exists public.sigcp_plus_meta (chave text primary key, valor text, atualizado_em text not null);
create table if not exists public.utilizadores_acessos (
 id bigint generated by default as identity primary key, utilizador_id bigint not null references public.utilizadores(id) on delete cascade,
 tipo_acesso text not null, criado_em text default current_timestamp::text, unique(utilizador_id, tipo_acesso)
);
create table if not exists public.welfares_individuais (
 id bigint generated by default as identity primary key, utilizador_id bigint not null references public.utilizadores(id) on delete cascade,
 data text not null, refeicao text not null, marcado integer not null default 1,
 criado_em text default current_timestamp::text, atualizado_em text default current_timestamp::text,
 unique(utilizador_id, data, refeicao)
);
create table if not exists public.ferias (
 id bigint generated by default as identity primary key, utilizador_id bigint not null references public.utilizadores(id) on delete cascade,
 data_hora_inicio text not null, data_hora_fim text not null, observacao text,
 criado_em text default current_timestamp::text, atualizado_em text default current_timestamp::text,
 companhia_aerea text, estado text not null default 'Aprovado', submetido_por bigint,
 submetido_em text, decidido_por bigint, decidido_em text, nota_decisao text,
 proposta_data_hora_inicio text, proposta_data_hora_fim text, proposta_observacao text,
 proposta_companhia_aerea text, motivo_fluxo text, fluxo_pedido_por bigint,
 fluxo_pedido_em text, avisos_aceites text, anulado_por bigint, anulado_em text, motivo_anulacao text
);
create table if not exists public.ferias_historico (
 id bigint generated by default as identity primary key, feria_id bigint not null references public.ferias(id) on delete cascade,
 utilizador_id bigint references public.utilizadores(id) on delete set null, acao text not null,
 estado_anterior text, estado_novo text, nota text, detalhes text, criado_em text default current_timestamp::text
);
create table if not exists public.ferias_notificacoes (
 id bigint generated by default as identity primary key, utilizador_id bigint not null references public.utilizadores(id) on delete cascade,
 feria_id bigint references public.ferias(id) on delete cascade, tipo text not null, titulo text not null,
 mensagem text, lida integer not null default 0, criado_em text default current_timestamp::text, canal text not null default 'pessoal'
);
create table if not exists public.sigcp_plus_recovery (
 user_id bigint primary key references public.utilizadores(id) on delete cascade,
 recovery_salt text not null, recovery_hash text not null, created_at text not null, used_at text
);
create table if not exists public.auditoria (
 id bigint generated by default as identity primary key, criado_em text not null default current_timestamp::text,
 utilizador_id bigint references public.utilizadores(id) on delete set null,
 utilizador_nim text not null default '', utilizador_identificacao text not null default '',
 acao text not null, metodo text not null, rota text not null, entidade text, entidade_id text,
 detalhes text not null default '{}', endereco_ip text
);
create index if not exists idx_auditoria_criado_em on public.auditoria(criado_em desc);
create index if not exists idx_ferias_utilizador on public.ferias(utilizador_id);
create index if not exists idx_notificacoes_utilizador on public.ferias_notificacoes(utilizador_id, lida);

-- Importação integral numa única transação. A lista é fixa para impedir injeção SQL.
create or replace function public.sigcp_import(p_payload jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare t text;
declare tabelas constant text[] := array[
 'utilizadores','app_settings','teams','welfares','team_membros','escala_loica','caixa_movimentos','day_offs','feriados','meses_trancados',
 'sigcp_plus_meta','utilizadores_acessos','welfares_individuais','ferias',
 'ferias_historico','ferias_notificacoes','sigcp_plus_recovery','auditoria'
];
begin
 if p_payload->>'formato' <> 'prt_welfare_database_export' then
   raise exception 'Ficheiro JSON SIGCP inválido';
 end if;
 truncate table auditoria, sigcp_plus_recovery, ferias_notificacoes, ferias_historico, caixa_movimentos, escala_loica, team_membros,
   ferias, welfares_individuais, utilizadores_acessos, sigcp_plus_meta,
   meses_trancados, feriados, day_offs, welfares, teams, app_settings, utilizadores restart identity cascade;
 foreach t in array tabelas loop
   if jsonb_array_length(coalesce(p_payload->'tabelas'->t->'registos', '[]'::jsonb)) > 0 then
     execute format('insert into public.%I select * from jsonb_populate_recordset(null::public.%I, $1)', t, t)
       using p_payload->'tabelas'->t->'registos';
   end if;
 end loop;
 perform setval(pg_get_serial_sequence('public.utilizadores','id'), coalesce((select max(id) from utilizadores),1), exists(select 1 from utilizadores));
 perform setval(pg_get_serial_sequence('public.teams','id'), coalesce((select max(id) from teams),1), exists(select 1 from teams));
 perform setval(pg_get_serial_sequence('public.welfares','id'), coalesce((select max(id) from welfares),1), exists(select 1 from welfares));
 perform setval(pg_get_serial_sequence('public.caixa_movimentos','id'), coalesce((select max(id) from caixa_movimentos),1), exists(select 1 from caixa_movimentos));
 perform setval(pg_get_serial_sequence('public.day_offs','id'), coalesce((select max(id) from day_offs),1), exists(select 1 from day_offs));
 perform setval(pg_get_serial_sequence('public.feriados','id'), coalesce((select max(id) from feriados),1), exists(select 1 from feriados));
 perform setval(pg_get_serial_sequence('public.utilizadores_acessos','id'), coalesce((select max(id) from utilizadores_acessos),1), exists(select 1 from utilizadores_acessos));
 perform setval(pg_get_serial_sequence('public.welfares_individuais','id'), coalesce((select max(id) from welfares_individuais),1), exists(select 1 from welfares_individuais));
 perform setval(pg_get_serial_sequence('public.ferias','id'), coalesce((select max(id) from ferias),1), exists(select 1 from ferias));
 perform setval(pg_get_serial_sequence('public.ferias_historico','id'), coalesce((select max(id) from ferias_historico),1), exists(select 1 from ferias_historico));
 perform setval(pg_get_serial_sequence('public.ferias_notificacoes','id'), coalesce((select max(id) from ferias_notificacoes),1), exists(select 1 from ferias_notificacoes));
 perform setval(pg_get_serial_sequence('public.auditoria','id'), coalesce((select max(id) from auditoria),1), exists(select 1 from auditoria));
end;
$$;

grant execute on function public.sigcp_import(jsonb) to anon, authenticated;
grant select on all tables in schema public to anon, authenticated;
alter table public.utilizadores enable row level security;
alter table public.app_settings enable row level security;
alter table public.welfares enable row level security;
alter table public.teams enable row level security;
alter table public.team_membros enable row level security;
alter table public.escala_loica enable row level security;
alter table public.caixa_movimentos enable row level security;
alter table public.day_offs enable row level security;
alter table public.feriados enable row level security;
alter table public.meses_trancados enable row level security;
alter table public.sigcp_plus_meta enable row level security;
alter table public.utilizadores_acessos enable row level security;
alter table public.welfares_individuais enable row level security;
alter table public.ferias enable row level security;
alter table public.ferias_historico enable row level security;
alter table public.ferias_notificacoes enable row level security;
alter table public.sigcp_plus_recovery enable row level security;
alter table public.auditoria enable row level security;

do $$ declare t text; begin
 foreach t in array array['utilizadores','app_settings','teams','welfares','team_membros','escala_loica','caixa_movimentos','day_offs','feriados','meses_trancados','sigcp_plus_meta','utilizadores_acessos','welfares_individuais','ferias','ferias_historico','ferias_notificacoes','sigcp_plus_recovery','auditoria'] loop
   execute format('drop policy if exists sigcp_read on public.%I', t);
   execute format('create policy sigcp_read on public.%I for select to anon, authenticated using (true)', t);
 end loop;
end $$;
